name: clang-format Check
on: 
    push:
        branches : [ main ]
    pull_request:
        branches : [ main ]
jobs:
  formatting-check:
    
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v2
        - name: Check
          run: |
              cd src
              clang-format -i *.t.cpp
              clang-format -i *.hpp
              clang-format -i *.cpp
              if [[ $(git status -s) ]]; then
                    git --no-pager diff
                    echo "Code does not adhere to the project standards. Run \"clang-format\".";
                    exit 1;
              else
                    echo "Code adheres to the project standards.";
                    exit 0;
              fi;